import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { email, metrics, dateRange, regionalData, categoryData } = body;

    if (!email) {
      return NextResponse.json({ error: 'Email is required' }, { status: 400 });
    }

    const apiKey = process.env.RESEND_API_KEY;

    // If no Resend API key, return the report data so the client can trigger mailto
    if (!apiKey) {
      return NextResponse.json({ 
        success: false, 
        fallback: 'mailto',
        message: 'RESEND_API_KEY not configured. Use PDF export or mailto fallback.' 
      }, { status: 200 });
    }

    // Import Resend dynamically
    const { Resend } = await import('resend');
    const resend = new Resend(apiKey);

    // Build HTML email
    const htmlContent = `
      <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 640px; margin: 0 auto; background: #fafafa; padding: 0;">
        <!-- Header -->
        <div style="background: linear-gradient(135deg, #1a1a1a, #2d2d2d); padding: 40px 32px; text-align: center;">
          <h1 style="color: #D4AF37; font-size: 28px; margin: 0 0 8px; letter-spacing: 4px;">GLOSSY</h1>
          <p style="color: #888; font-size: 12px; margin: 0; letter-spacing: 2px; text-transform: uppercase;">Analytics Report — ${dateRange.toUpperCase()}</p>
        </div>

        <!-- Metrics -->
        <div style="padding: 32px;">
          <h2 style="font-size: 18px; color: #1a1a1a; margin: 0 0 20px; letter-spacing: 1px;">KEY METRICS</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 16px; background: white; border: 1px solid #eee; text-align: center;">
                <p style="font-size: 11px; color: #999; margin: 0 0 6px; text-transform: uppercase; letter-spacing: 1px;">Revenue</p>
                <p style="font-size: 22px; color: #1a1a1a; margin: 0; font-weight: bold;">${metrics.totalRevenue?.toFixed(2)} LYD</p>
              </td>
              <td style="padding: 16px; background: white; border: 1px solid #eee; text-align: center;">
                <p style="font-size: 11px; color: #999; margin: 0 0 6px; text-transform: uppercase; letter-spacing: 1px;">Orders</p>
                <p style="font-size: 22px; color: #1a1a1a; margin: 0; font-weight: bold;">${metrics.totalOrders}</p>
              </td>
            </tr>
            <tr>
              <td style="padding: 16px; background: white; border: 1px solid #eee; text-align: center;">
                <p style="font-size: 11px; color: #999; margin: 0 0 6px; text-transform: uppercase; letter-spacing: 1px;">Avg. Order</p>
                <p style="font-size: 22px; color: #1a1a1a; margin: 0; font-weight: bold;">${metrics.aov?.toFixed(2)} LYD</p>
              </td>
              <td style="padding: 16px; background: white; border: 1px solid #eee; text-align: center;">
                <p style="font-size: 11px; color: #999; margin: 0 0 6px; text-transform: uppercase; letter-spacing: 1px;">Profit Margin</p>
                <p style="font-size: 22px; color: #1a1a1a; margin: 0; font-weight: bold;">${metrics.profitMargin?.toFixed(1)}%</p>
              </td>
            </tr>
          </table>
        </div>

        <!-- Top Regions -->
        ${regionalData && regionalData.length > 0 ? `
        <div style="padding: 0 32px 32px;">
          <h2 style="font-size: 18px; color: #1a1a1a; margin: 0 0 16px; letter-spacing: 1px;">TOP REGIONS</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="background: #1a1a1a; color: white;">
              <th style="padding: 12px 16px; text-align: left; font-size: 11px; letter-spacing: 1px;">REGION</th>
              <th style="padding: 12px 16px; text-align: right; font-size: 11px; letter-spacing: 1px;">REVENUE</th>
            </tr>
            ${regionalData.slice(0, 5).map((r: any, i: number) => `
              <tr style="background: ${i % 2 === 0 ? 'white' : '#f9f9f9'};">
                <td style="padding: 12px 16px; font-size: 14px; border-bottom: 1px solid #eee;">${r.name}</td>
                <td style="padding: 12px 16px; font-size: 14px; text-align: right; font-weight: bold; border-bottom: 1px solid #eee;">${r.value?.toFixed(2)} LYD</td>
              </tr>
            `).join('')}
          </table>
        </div>
        ` : ''}

        <!-- Footer -->
        <div style="background: #1a1a1a; padding: 24px 32px; text-align: center;">
          <p style="color: #D4AF37; font-size: 11px; margin: 0; letter-spacing: 2px;">GENERATED BY GLOSSY ANALYTICS ENGINE</p>
          <p style="color: #666; font-size: 10px; margin: 8px 0 0;">This is an automated report. Do not reply to this email.</p>
        </div>
      </div>
    `;

    const { data, error } = await resend.emails.send({
      from: 'GLOSSY Analytics <onboarding@resend.dev>',
      to: [email],
      subject: `GLOSSY Analytics Report — ${dateRange.toUpperCase()}`,
      html: htmlContent,
    });

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true, id: data?.id });
  } catch (err: any) {
    console.error('Export email error:', err);
    return NextResponse.json({ error: err.message || 'Internal server error' }, { status: 500 });
  }
}
